name: Frontend - Build and Deploy to S3 + CloudFront

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-s3-cf.yml'

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Build
        working-directory: frontend
        env:
          CI: false
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync to S3
        run: |
          if [ -z "${{ secrets.FRONTEND_BUCKET_NAME }}" ]; then
            echo "FRONTEND_BUCKET_NAME secret is required" && exit 1
          fi
          aws s3 sync frontend/build "s3://${{ secrets.FRONTEND_BUCKET_NAME }}" --delete

      - name: Invalidate CloudFront cache
        run: |
          if [ -z "${{ secrets.CF_DISTRIBUTION_ID }}" ]; then
            echo "CF_DISTRIBUTION_ID secret is required" && exit 1
          fi
          aws cloudfront create-invalidation --distribution-id "${{ secrets.CF_DISTRIBUTION_ID }}" --paths "/*"
